: emit $20001 ! ; : . $20002 ! ;  : .. dup . ; 
: (here) $30001 ; : (last) $30002 ;
: base   $30003 ; : state  $30004 ; 
: here (here) @ ; : last (last) @ ; 
: dict-start 0 ; : dict-end $30006 @ 1- ; 
: free dict-end here - ; : used here dict-start - ;
: cr #13 emit #10 emit ; : space $20 emit ;
: .s '(' emit >r >r >r >r .. r> .. r> .. r> .. r> .. space ')' emit ;
: count dup 1+ swap c@ ;
: type begin >r dup c@ emit 1+ r> 1- dup while drop drop ;
: words cr last begin dup 5 + count type space w@ dup while drop ;
: .word dup . dup 2 + w@ . space 5 + count type cr ;
: wordsl cr last begin dup .word w@ dup while drop ;
: bm begin wdtfeed 1- dup while drop ;
: pin! $10000 + ! ; : pin@ $10000 + @ ;
: led! 13 pin! ; : pin>led pin@ led! ;
: apin-base 54 ; : apin# apin-base + ;
: apin! apin# $10000 + ! ; : apin@ apin# $10000 + @ ; : apin? apin@ . ;
variable running : ?running running @ ;
: on 1 swap ! ; : off 0 swap ! ;
: run running on ; : stop running off ;
: main ?running if 36 pin>led 0 apin? cr then $FFFF drop ;
: k 1000 * ; : mil k k ; : go cr 's' emit bm cr 'e' emit ;
: ok cr 'o' emit 'k' emit cr ; ok
: .char dup c@ . 1+ ; : .char4 .char .char .char .char ; 
: dump begin >r dup .char 1+ r> 1- dup while drop drop ;
: dump-ft over - dump ;
: dump-16 dup . ':' emit space .char4 .char4 .char4 .char4 ;
: dump-dict here . last . 0 begin cr dump-16 here over > while drop ;
: auto-run 0 w! ; : auto-run-last last 1+ 1+ w@ auto-run ;
